spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=FleetManagementSystem
spring.data.mongodb.auto-index-creation=true
#mongoTemplate.indexOps("CompanyConfiguration").ensureIndex(new Index("companyName", Direction.ASC).unique());
#mongoTemplate.indexOps("VehicleConfiguration").ensureIndex(new Index("vehicleName", Direction.ASC).unique());
#mongoTemplate.indexOps("VehicleFleet").ensureIndex(new Index("name", Direction.ASC).unique());
#mongoTemplate.indexOps("VehicleServices").ensureIndex(new Index("serviceName", Direction.ASC).unique());
# Prototype API: accept connections only from this machine.
server.address=127.0.0.1
